# This workflow runs tests and reports code coverage.

# We need a workflow name to be able to schedule it from Github UI
name: TestCoverage

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  image_id: ${{ secrets.IMAGE_ID }}
  keyname: ${{ secrets.KEYNAME }}
  security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
  subnet_id: ${{ secrets.SUBNET_ID }}

jobs:
  StartTheRunner:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create Key and Start EC2
        id: startec2
        run: |
          aws ec2 create-key-pair --key-name $keyname --query "KeyMaterial" --output text >> $keyname.pem
          chmod 400 $keyname.pem
          instance_id=$(aws ec2 run-instances --image-id $image_id --count 1 --instance-type p3.2xlarge --key-name $keyname --security-group-ids $security_group_id --subnet-id $subnet_id --query "Instances[].InstanceId" --output text)
          aws ec2 wait instance-status-ok --instance-ids $instance_id
          echo instance_id=$instance_id >> $GITHUB_ENV
          echo "::set-output name=ec2_instance_id::$instance_id

  # The job ID has to match repo settings for PR required checks
  TestCoverage:
    needs: StartTheRunner
    runs-on: gpu-runner
    # Run jobs for a couple of Python versions.
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    name: TestCoverage - Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2

      - name: Get orquestra-quantum
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-quantum
          path: orquestra-quantum

      - uses: ./subtrees/z_quantum_actions/actions/coverage

  Terminate-ec2:
    name: Terminate EC2 instance
    needs:
      - StartTheRunner
      - TestCoverage
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terminate the instance
        run: aws ec2 terminate-instances --instance-ids ${{needs.StartTheRunner.outputs.ec2-instance-id}} --output text

  Delete-key-pair:
    name: Clean key-pair
    needs:
      - StartTheRunner
      - TestCoverage
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Remove keypair
        run: aws ec2 delete-key-pair --key-name ${{secrets.KEYNAME }}
